##HADOOP
export HADOOP_HOME=/hadoop-3.2.1
export PATH=$HADOOP_HOME/bin:$PATH
export PATH=$HADOOP_HOME/sbin:$PATH
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
export HADOOP_STREAMING=$HADOOP_HOME/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar
export HADOOP_LOG_DIR=$HADOOP_HOME/logs

##JAVA
export JAVA_HOME=/jre1.8.0_251
export PATH=$PATH:$JAVA_HOME/bin

##HIVE
export HIVE_HOME=/apache-hive-3.1.2-bin
export HIVE_CONF_DIR=$HIVE_HOME/conf
export PATH=$HIVE_HOME/bin:$PATH
export CLASSPATH=$CLASSPATH:$HADOOP_HOME/lib/*:.
export CLASSPATH=$CLASSPATH:$HIVE_HOME/lib/*:.

#HCATALOG
export HCAT_HOME=$HIVE_HOME/hcatalog
export HCAT_LOG_DIR=/var/log/hcatalog

#SPARK
SPARK_HOME=/spark-2.4.6-bin-hadoop2.7/

#PYTHON
export PYSPARK_PYTHON=/Python-3.6.0/python

alias spark-submit=/spark-2.4.6-bin-hadoop2.7/bin/spark-submit
alias beeline="$HIVE_HOME/bin/beeline -u jdbc:hive2://" #or $HIVE_HOME/bin/beeline -u jdbc:hive2://$HS2_HOST:$HS2_PORT
alias pyspark=/spark-2.4.6-bin-hadoop2.7/bin/pyspark
alias hcat=$HIVE_HOME/hcatalog/bin/hcat
